Default: &defaults
  database: rivierarb.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: rivierarb_test.sqlite3
  <<: *defaults

Staging:
  database: rivierarb_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: rivierarb_production.sqlite3
  poolsize: 100
  <<: *defaults
